name: NormCI

# Controls when the action will run.
on:
  push:
    branches: [ "*" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  norm:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout git repository
        uses: actions/checkout@v2

      - name: Install Norminette
        run: |
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install norminette
      - name: Run Norminette
        run: norminette libft/.

      - name: Run Norminette
        run: norminette srcs/.
